[package]
name = "calcr"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2.0", features = ["tokio"] }
env_logger = "0.11"
tera = "1.0"
serde = "1.0.215"
rand = "0.8.5"
clap = { version = "4.5.20", features = ["derive"] }
